# Generated by Django 4.2.21 - merged initial migration for TiDB/MySQL compatibility

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, help_text='e.g., Kerala Cuisine, North Indian, etc.', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef Profile',
                'verbose_name_plural': 'Chef Profiles',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast (6:00 AM - 12:00 PM)'), ('Lunch', 'Lunch (12:00 PM - 3:30 PM)'), ('Snacks', 'Snacks (3:30 PM - 6:30 PM)'), ('Dinner', 'Dinner (6:30 PM - 10:00 PM)')], default='Breakfast', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_time', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Out of 5', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'chef'}, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ('-created_at',),
            },
        ),
    ]
