# Generated by Django 4.2.21 on 2026-05-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chef', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='chef',
            field=models.ForeignKey(limit_choices_to={'role': 'chef'}, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
