# Generated by Django 4.2.21 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_add_chef_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an external image URL (e.g. from Imgur or Google Drive)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast (6:00 AM - 12:00 PM)'), ('Lunch', 'Lunch (12:00 PM - 3:30 PM)'), ('Snacks', 'Snacks (3:30 PM - 6:30 PM)'), ('Dinner', 'Dinner (6:30 PM - 3:00 AM)')], default='Breakfast', max_length=20),
        ),
    ]
